### ISSUE TITLE
asp.net configuration 

### ISSUE THREAD

**Issue by hossam2015** [no81no/jplist-asp-net#1]
Hello,

I tried everything with the ASP.NET and SQL Server to make it work without any sucess 

Can you please tell me how to make it work 

Thanx alot for your great work this is the new best thing for data view

Regards

**Comment by 1rosehip** [comment]
Hello,
Thank you for the feedback.
Can you please describe what errors you get?

Thanks

**Comment by hossam2015** [comment]
thats the problem no error appear 

I add the connection and create the db and table with the data but no data appear when I try to view it
connectionString="Data Source=127.0.0.1;Initial Catalog=jplist;User ID=sa;Password=mypassword"

**Comment by hossam2015** [comment]
the ajax-loader-line.gif image keep going right to left thats it when trying to view the page without showing any data

**Comment by 1rosehip** [comment]
Please try to add a breakpoint  to ~/WEB/JPListHandler.cs and check what exception you get there.

**Comment by hossam2015** [comment]
I tried breakpoint when I do run it run but it donot even call the breakpoint

**Comment by 1rosehip** [comment]
If so, maybe there are errors in browser console?

**Comment by hossam2015** [comment]
nothing in the console 

even I tried the old version of jplist it show no data to view but the data are there

does it require specific version of the .net framwork ???

**Comment by 1rosehip** [comment]
No, it doesn't require a specific version of .net framework version.
Can you share a link to your page so I could see this issue?

**Comment by 1rosehip** [comment]
The project is updated
